#*-----------------------------------------------------------------------------
#* Author: Boris Vinogradov(nis) : no111u3@gmail.com
#* File: Makefile
#* Type: Makefile
#* Project: f4examples/00-base
#* 2012
#*-----------------------------------------------------------------------------
# Compilator prefix
CROSS_PREFIX=arm-softfloat-linux-gnueabi
# Compilators and utils
CC=$(CROSS_PREFIX)gcc
OBJCOPY=$(CROSS_PREFIX)objcopy